### ISSUE TITLE
Raid system should be off by default | Check for autohost vs manual

### ISSUE THREAD

**Issue by shipofgenius** [TalimaVale/BeastieBot#15] opened 2017-05-18 09:14 UTC
```
[08:59] info: Joined #trugamer_maniac
[08:59] info: [#trugamer_maniac] <matrix_agent>: Hello everybody! :D I have awoken! Welcome back to trugamer_maniac's channel!
Beastie's broadcasterID is: #
This is our channel id: 143283241
[09:00] info: [#trugamer_maniac] Now hosting chefjohnreed for 0 viewer(s).
We are hosting another channel :O
[09:00] info: [#trugamer_maniac] <matrix_agent>: Time to raid! :D rawr
[09:00] info: Executing command: JOIN #chefjohnreed
BEASTIE has joined another channel: undefined
BEASTIE is waiting 2 minutes for the raid.
[09:00] info: Joined #chefjohnreed

```

**Comment by scryptonite** [comment] 2017-05-18 16:05
@shipofgenius Yeah he does. 

This issue is technically a duplicate of #7 and should be resolved once I submit a PR for my [`scryptonite-patch-raids`][scryptonite-patch-raids] branch. I'd actually appreciate feedback if you'd like to check it out and confirm that my changes to the raiding system work :P 

[scryptonite-patch-raids]: https://github.com/scryptonite/BeastieBot/tree/scryptonite-patch-raids

**Comment by shipofgenius** [comment] 2017-05-20 04:21
Cool! Do I pull from the branch of your fork? Or just pull your whole branch

**Comment by scryptonite** [comment] 2017-05-20 04:26
@shipofgenius Yeah, you just need pull that branch from my fork. :thumbsup:

**Comment by shipofgenius** [comment] 2017-05-20 21:41
Tested and confirmed. Raid system is now off by default. #7 #15

**Closed as completed** 2017-05-24 07:55 UTC
